channel:
  name: test
  youtube_channel_id: UCZZZZ

final_target_duration: 2

subreddits:
  - testrarepuppers
  - AnimalsBeingDerps

post:
  min_duration: 1
  max_duration: 15
  min_score: 100
  min_ratio: 0.7

audio:
  music_detection:
    enabled: true
    engine: ina

music:
  enabled: true
  replace_detected_music: true

commentary:
  theme: funny
  every_nth: 2
  tts_voices:
    gemini: Kore

thumbnail:
  min_score: 500
  min_ratio: 0.8
